/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = com.usemoon.MoonSDK.Client.OpenAPIDateConverter;

namespace com.usemoon.MoonSDK.Model
{
    /// <summary>
    /// The abi to parse the log object of the contract
    /// </summary>
    [DataContract(Name = "AbiItem")]
    public partial class AbiItem : IEquatable<AbiItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AbiItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AbiItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AbiItem" /> class.
        /// </summary>
        /// <param name="anonymous">anonymous.</param>
        /// <param name="constant">constant.</param>
        /// <param name="inputs">inputs.</param>
        /// <param name="name">name.</param>
        /// <param name="outputs">outputs.</param>
        /// <param name="payable">payable.</param>
        /// <param name="stateMutability">stateMutability.</param>
        /// <param name="type">type (required).</param>
        /// <param name="gas">gas.</param>
        public AbiItem(bool anonymous = default(bool), bool constant = default(bool), List<AbiInput> inputs = default(List<AbiInput>), string name = default(string), List<AbiOutput> outputs = default(List<AbiOutput>), bool payable = default(bool), string stateMutability = default(string), string type = default(string), double gas = default(double))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for AbiItem and cannot be null");
            }
            this.Type = type;
            this.Anonymous = anonymous;
            this.Constant = constant;
            this.Inputs = inputs;
            this.Name = name;
            this.Outputs = outputs;
            this.Payable = payable;
            this.StateMutability = stateMutability;
            this.Gas = gas;
        }

        /// <summary>
        /// Gets or Sets Anonymous
        /// </summary>
        [DataMember(Name = "anonymous", EmitDefaultValue = true)]
        public bool Anonymous { get; set; }

        /// <summary>
        /// Gets or Sets Constant
        /// </summary>
        [DataMember(Name = "constant", EmitDefaultValue = true)]
        public bool Constant { get; set; }

        /// <summary>
        /// Gets or Sets Inputs
        /// </summary>
        [DataMember(Name = "inputs", EmitDefaultValue = false)]
        public List<AbiInput> Inputs { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Outputs
        /// </summary>
        [DataMember(Name = "outputs", EmitDefaultValue = false)]
        public List<AbiOutput> Outputs { get; set; }

        /// <summary>
        /// Gets or Sets Payable
        /// </summary>
        [DataMember(Name = "payable", EmitDefaultValue = true)]
        public bool Payable { get; set; }

        /// <summary>
        /// Gets or Sets StateMutability
        /// </summary>
        [DataMember(Name = "stateMutability", EmitDefaultValue = false)]
        public string StateMutability { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Gas
        /// </summary>
        [DataMember(Name = "gas", EmitDefaultValue = false)]
        public double Gas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AbiItem {\n");
            sb.Append("  Anonymous: ").Append(Anonymous).Append("\n");
            sb.Append("  Constant: ").Append(Constant).Append("\n");
            sb.Append("  Inputs: ").Append(Inputs).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Outputs: ").Append(Outputs).Append("\n");
            sb.Append("  Payable: ").Append(Payable).Append("\n");
            sb.Append("  StateMutability: ").Append(StateMutability).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Gas: ").Append(Gas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AbiItem);
        }

        /// <summary>
        /// Returns true if AbiItem instances are equal
        /// </summary>
        /// <param name="input">Instance of AbiItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AbiItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Anonymous == input.Anonymous ||
                    this.Anonymous.Equals(input.Anonymous)
                ) && 
                (
                    this.Constant == input.Constant ||
                    this.Constant.Equals(input.Constant)
                ) && 
                (
                    this.Inputs == input.Inputs ||
                    this.Inputs != null &&
                    input.Inputs != null &&
                    this.Inputs.SequenceEqual(input.Inputs)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Outputs == input.Outputs ||
                    this.Outputs != null &&
                    input.Outputs != null &&
                    this.Outputs.SequenceEqual(input.Outputs)
                ) && 
                (
                    this.Payable == input.Payable ||
                    this.Payable.Equals(input.Payable)
                ) && 
                (
                    this.StateMutability == input.StateMutability ||
                    (this.StateMutability != null &&
                    this.StateMutability.Equals(input.StateMutability))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Gas == input.Gas ||
                    this.Gas.Equals(input.Gas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Anonymous.GetHashCode();
                hashCode = (hashCode * 59) + this.Constant.GetHashCode();
                if (this.Inputs != null)
                {
                    hashCode = (hashCode * 59) + this.Inputs.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Outputs != null)
                {
                    hashCode = (hashCode * 59) + this.Outputs.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Payable.GetHashCode();
                if (this.StateMutability != null)
                {
                    hashCode = (hashCode * 59) + this.StateMutability.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Gas.GetHashCode();
                return hashCode;
            }
        }

    }

}
