/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = com.usemoon.MoonSDK.Client.OpenAPIDateConverter;

namespace com.usemoon.MoonSDK.Model
{
    /// <summary>
    /// AvailablePaymentMethod
    /// </summary>
    [DataContract(Name = "AvailablePaymentMethod")]
    public partial class AvailablePaymentMethod : IEquatable<AvailablePaymentMethod>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailablePaymentMethod" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AvailablePaymentMethod() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailablePaymentMethod" /> class.
        /// </summary>
        /// <param name="icon">icon (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="paymentTypeId">paymentTypeId (required).</param>
        public AvailablePaymentMethod(string icon = default(string), string name = default(string), string paymentTypeId = default(string))
        {
            // to ensure "icon" is required (not null)
            if (icon == null)
            {
                throw new ArgumentNullException("icon is a required property for AvailablePaymentMethod and cannot be null");
            }
            this.Icon = icon;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AvailablePaymentMethod and cannot be null");
            }
            this.Name = name;
            // to ensure "paymentTypeId" is required (not null)
            if (paymentTypeId == null)
            {
                throw new ArgumentNullException("paymentTypeId is a required property for AvailablePaymentMethod and cannot be null");
            }
            this.PaymentTypeId = paymentTypeId;
        }

        /// <summary>
        /// Gets or Sets Icon
        /// </summary>
        [DataMember(Name = "icon", IsRequired = true, EmitDefaultValue = true)]
        public string Icon { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets PaymentTypeId
        /// </summary>
        [DataMember(Name = "paymentTypeId", IsRequired = true, EmitDefaultValue = true)]
        public string PaymentTypeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AvailablePaymentMethod {\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PaymentTypeId: ").Append(PaymentTypeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AvailablePaymentMethod);
        }

        /// <summary>
        /// Returns true if AvailablePaymentMethod instances are equal
        /// </summary>
        /// <param name="input">Instance of AvailablePaymentMethod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AvailablePaymentMethod input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Icon == input.Icon ||
                    (this.Icon != null &&
                    this.Icon.Equals(input.Icon))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.PaymentTypeId == input.PaymentTypeId ||
                    (this.PaymentTypeId != null &&
                    this.PaymentTypeId.Equals(input.PaymentTypeId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Icon != null)
                {
                    hashCode = (hashCode * 59) + this.Icon.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.PaymentTypeId != null)
                {
                    hashCode = (hashCode * 59) + this.PaymentTypeId.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
