/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = com.usemoon.MoonSDK.Client.OpenAPIDateConverter;

namespace com.usemoon.MoonSDK.Model
{
    /// <summary>
    /// SignMessage
    /// </summary>
    [DataContract(Name = "SignMessage")]
    public partial class SignMessage : IEquatable<SignMessage>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignMessage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignMessage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignMessage" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="data">data (required).</param>
        /// <param name="encoding">encoding.</param>
        /// <param name="header">header.</param>
        /// <param name="signtype">signtype.</param>
        public SignMessage(string name = default(string), string data = default(string), string encoding = default(string), bool header = default(bool), bool signtype = default(bool))
        {
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for SignMessage and cannot be null");
            }
            this.Data = data;
            this.Name = name;
            this.Encoding = encoding;
            this.Header = header;
            this.Signtype = signtype;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public string Data { get; set; }

        /// <summary>
        /// Gets or Sets Encoding
        /// </summary>
        [DataMember(Name = "encoding", EmitDefaultValue = false)]
        public string Encoding { get; set; }

        /// <summary>
        /// Gets or Sets Header
        /// </summary>
        [DataMember(Name = "header", EmitDefaultValue = true)]
        public bool Header { get; set; }

        /// <summary>
        /// Gets or Sets Signtype
        /// </summary>
        [DataMember(Name = "signtype", EmitDefaultValue = true)]
        public bool Signtype { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignMessage {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Encoding: ").Append(Encoding).Append("\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Signtype: ").Append(Signtype).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SignMessage);
        }

        /// <summary>
        /// Returns true if SignMessage instances are equal
        /// </summary>
        /// <param name="input">Instance of SignMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SignMessage input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Data == input.Data ||
                    (this.Data != null &&
                    this.Data.Equals(input.Data))
                ) && 
                (
                    this.Encoding == input.Encoding ||
                    (this.Encoding != null &&
                    this.Encoding.Equals(input.Encoding))
                ) && 
                (
                    this.Header == input.Header ||
                    this.Header.Equals(input.Header)
                ) && 
                (
                    this.Signtype == input.Signtype ||
                    this.Signtype.Equals(input.Signtype)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Data != null)
                {
                    hashCode = (hashCode * 59) + this.Data.GetHashCode();
                }
                if (this.Encoding != null)
                {
                    hashCode = (hashCode * 59) + this.Encoding.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Header.GetHashCode();
                hashCode = (hashCode * 59) + this.Signtype.GetHashCode();
                return hashCode;
            }
        }

    }

}
