/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = com.usemoon.MoonSDK.Client.OpenAPIDateConverter;

namespace com.usemoon.MoonSDK.Model
{
    /// <summary>
    /// SupportedAssetResponseAssetsInner
    /// </summary>
    [DataContract(Name = "SupportedAssetResponse_assets_inner")]
    public partial class SupportedAssetResponseAssetsInner : IEquatable<SupportedAssetResponseAssetsInner>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupportedAssetResponseAssetsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SupportedAssetResponseAssetsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SupportedAssetResponseAssetsInner" /> class.
        /// </summary>
        /// <param name="crypto">crypto (required).</param>
        /// <param name="paymentMethods">paymentMethods (required).</param>
        /// <param name="fiat">fiat (required).</param>
        public SupportedAssetResponseAssetsInner(List<string> crypto = default(List<string>), List<string> paymentMethods = default(List<string>), string fiat = default(string))
        {
            // to ensure "crypto" is required (not null)
            if (crypto == null)
            {
                throw new ArgumentNullException("crypto is a required property for SupportedAssetResponseAssetsInner and cannot be null");
            }
            this.Crypto = crypto;
            // to ensure "paymentMethods" is required (not null)
            if (paymentMethods == null)
            {
                throw new ArgumentNullException("paymentMethods is a required property for SupportedAssetResponseAssetsInner and cannot be null");
            }
            this.PaymentMethods = paymentMethods;
            // to ensure "fiat" is required (not null)
            if (fiat == null)
            {
                throw new ArgumentNullException("fiat is a required property for SupportedAssetResponseAssetsInner and cannot be null");
            }
            this.Fiat = fiat;
        }

        /// <summary>
        /// Gets or Sets Crypto
        /// </summary>
        [DataMember(Name = "crypto", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Crypto { get; set; }

        /// <summary>
        /// Gets or Sets PaymentMethods
        /// </summary>
        [DataMember(Name = "paymentMethods", IsRequired = true, EmitDefaultValue = true)]
        public List<string> PaymentMethods { get; set; }

        /// <summary>
        /// Gets or Sets Fiat
        /// </summary>
        [DataMember(Name = "fiat", IsRequired = true, EmitDefaultValue = true)]
        public string Fiat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupportedAssetResponseAssetsInner {\n");
            sb.Append("  Crypto: ").Append(Crypto).Append("\n");
            sb.Append("  PaymentMethods: ").Append(PaymentMethods).Append("\n");
            sb.Append("  Fiat: ").Append(Fiat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SupportedAssetResponseAssetsInner);
        }

        /// <summary>
        /// Returns true if SupportedAssetResponseAssetsInner instances are equal
        /// </summary>
        /// <param name="input">Instance of SupportedAssetResponseAssetsInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SupportedAssetResponseAssetsInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Crypto == input.Crypto ||
                    this.Crypto != null &&
                    input.Crypto != null &&
                    this.Crypto.SequenceEqual(input.Crypto)
                ) && 
                (
                    this.PaymentMethods == input.PaymentMethods ||
                    this.PaymentMethods != null &&
                    input.PaymentMethods != null &&
                    this.PaymentMethods.SequenceEqual(input.PaymentMethods)
                ) && 
                (
                    this.Fiat == input.Fiat ||
                    (this.Fiat != null &&
                    this.Fiat.Equals(input.Fiat))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Crypto != null)
                {
                    hashCode = (hashCode * 59) + this.Crypto.GetHashCode();
                }
                if (this.PaymentMethods != null)
                {
                    hashCode = (hashCode * 59) + this.PaymentMethods.GetHashCode();
                }
                if (this.Fiat != null)
                {
                    hashCode = (hashCode * 59) + this.Fiat.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
