/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = com.usemoon.MoonSDK.Client.OpenAPIDateConverter;

namespace com.usemoon.MoonSDK.Model
{
    /// <summary>
    /// TransactionInputSupportedParamsPartnerData
    /// </summary>
    [DataContract(Name = "TransactionInput_supportedParams_partnerData")]
    public partial class TransactionInputSupportedParamsPartnerData : IEquatable<TransactionInputSupportedParamsPartnerData>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionInputSupportedParamsPartnerData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionInputSupportedParamsPartnerData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionInputSupportedParamsPartnerData" /> class.
        /// </summary>
        /// <param name="redirectUrl">redirectUrl (required).</param>
        public TransactionInputSupportedParamsPartnerData(TransactionInputSupportedParamsPartnerDataRedirectUrl redirectUrl = default(TransactionInputSupportedParamsPartnerDataRedirectUrl))
        {
            // to ensure "redirectUrl" is required (not null)
            if (redirectUrl == null)
            {
                throw new ArgumentNullException("redirectUrl is a required property for TransactionInputSupportedParamsPartnerData and cannot be null");
            }
            this.RedirectUrl = redirectUrl;
        }

        /// <summary>
        /// Gets or Sets RedirectUrl
        /// </summary>
        [DataMember(Name = "redirectUrl", IsRequired = true, EmitDefaultValue = true)]
        public TransactionInputSupportedParamsPartnerDataRedirectUrl RedirectUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionInputSupportedParamsPartnerData {\n");
            sb.Append("  RedirectUrl: ").Append(RedirectUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionInputSupportedParamsPartnerData);
        }

        /// <summary>
        /// Returns true if TransactionInputSupportedParamsPartnerData instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionInputSupportedParamsPartnerData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionInputSupportedParamsPartnerData input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RedirectUrl == input.RedirectUrl ||
                    (this.RedirectUrl != null &&
                    this.RedirectUrl.Equals(input.RedirectUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RedirectUrl != null)
                {
                    hashCode = (hashCode * 59) + this.RedirectUrl.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
